# Generated by Django 4.1 on 2022-08-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
