# Generated by Django 4.1 on 2022-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifications',
            name='fromDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='toDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
