# Generated by Django 4.1 on 2022-08-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_qualifications_fromdate_qualifications_todate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.TextField(),
        ),
    ]
