# Generated by Django 4.1 on 2022-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='regid',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
