# Generated by Django 4.1 on 2022-08-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employee_regid'),
    ]

    operations = [
        migrations.CreateModel(
            name='empID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.IntegerField()),
            ],
        ),
    ]
